config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, format: :json do
    resources :stations, only: [] do
      resources :styles, only: :index, controller: :station_styles
    end
  end

  namespace :station_admin do
    resources :stations, only: [] do
      resources :station_styles, only: [:index, :create, :destroy]
    end

    resources :styles, only: [:index, :edit, :update, :destroy] do
      resources :manage_style_synonyms, only: [:create, :destroy]
    end

    resources :style_synonyms, only: [:index, :edit, :update] do
      resources :manage_styles, only: [:create, :destroy]
    end
  end
end

app/models/style.rb
# frozen_string_literal: true

require 'globalize'

class Style < ApplicationRecord
  include NormalizeSlugConcern

  translates :name, :slug, :tooltip, :description

  accepts_nested_attributes_for :translations

  extend FriendlyId

  friendly_id :slug_candidates, use: [:slugged, :globalize]

  def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end

  searchkick word_start: [:name]

  include TranslationsConcern
  include ElasticsearchGlobalizeConcern

  has_many :style_photos, dependent: :destroy

  has_many :style_style_synonyms, dependent: :destroy

  has_many :style_synonyms, through: :style_style_synonyms

  has_many :order_styles, dependent: :destroy

  has_many :orders, through: :order_styles

  has_many :station_styles, dependent: :destroy

  has_many :stations, through: :station_styles

  has_many :seo_blocks, dependent: :nullify

  accepts_nested_attributes_for :style_photos, allow_destroy: true

  scope :with_country, ->(code) { where('? = ANY(permitted_countries)', code) }

  scope :with_translations_and_photos, -> { includes(:translations, :style_photos) }

  validate :check_max_photos, on: [:create, :update]

  def to_param
    # From rails
    id&.to_s
  end

  def search_data
    {
      name: name,
      slug: slug,
      permitted_countries: permitted_countries,
      translations: translatable_columns_values
    }.merge(translated_attributes_for_elasticsearch)
  end

  def add_country(code)
    permitted_countries << code if permitted_countries.exclude?(code)

    save!

    reindex
  end

  def remove_country(code)
    permitted_countries.delete(code) if permitted_countries.include?(code)

    save!

    reindex
  end

  def check_max_photos
    errors.add(:base, 'must not contain more than 3 photos') if style_photos.size > 3
  end

  def should_generate_new_friendly_id?
    globalize.fetch_without_fallbacks(:slug).blank? && globalize.fetch_without_fallbacks(:name).present?
  end

  def normalize_friendly_id(text)
    text.to_slug.normalize(
      transliterations: BabosaTransliterator.get_transliterator(
        FakeFallback.get_locale(Globalize.locale)
      )
    ).to_s.downcase.dasherize
  end
end

app/controllers/station_admin/base_controller.rb
# frozen_string_literal: true

if !Object.const_defined?('StationAdmin::BaseController')
  module StationAdmin
    class BaseController < ActionController::Base
      layout 'application'
    end
  end
end

app/controllers/station_admin/manage_style_synonyms_controller.rb
# frozen_string_literal: true

module StationAdmin
  class ManageStyleSynonymsController < BaseController
    def create
      @style = Style.find(params[:style_id])
      @style_synonym = StyleSynonym.find(params[:id])
      @style.style_synonyms << @style_synonym
      # @style.reindex
      redirect_to edit_station_admin_style_path(@style)
    end

    def destroy
      @style = Style.find(params[:style_id])
      @style_synonym = StyleSynonym.find(params[:id])
      @style.style_synonyms.destroy(@style_synonym)
      # @style.reindex
      redirect_to edit_station_admin_style_path(@style)
    end
  end
end

app/controllers/station_admin/manage_styles_controller.rb
# frozen_string_literal: true

module StationAdmin
  class ManageStylesController < BaseController
    def create
      @style_synonym = StyleSynonym.find(params[:style_synonym_id])
      @style = Style.find(params[:id])
      @style_synonym.styles << @style
      # @style_synonym.reindex
      redirect_to edit_station_admin_style_synonym_path(@style_synonym)
    end

    def destroy
      @style_synonym = StyleSynonym.find(params[:style_synonym_id])
      @style = Style.find(params[:id])
      @style_synonym.styles.destroy(@style)
      # @style_synonym.reindex
      redirect_to edit_station_admin_style_synonym_path(@style_synonym)
    end
  end
end

app/controllers/station_admin/station_styles_controller.rb
# frozen_string_literal: true

module StationAdmin
  class StationStylesController < BaseController
    def index
      @station = Station.find(params[:station_id])
      @active_tab = 'station_styles'
      params[:display_menu_for_station] = true
      @styles = Style.includes(:translations)
                     .with_country(current_user.country_code) - @station.styles.includes(:translations)

      respond_to do |format|
        format.html
        format.json do
          render json: StationStyleDatatable.new(params,
                                                 station: @station,
                                                 view_context: view_context)
        end
      end
    end

    def create
      @station = Station.find(params[:station_id])
      @style = Style.find(params[:id])
      @station.styles << @style
      # @station.reindex
      redirect_to station_admin_station_station_styles_path(@station)
    end

    def destroy
      @station = Station.find(params[:station_id])
      @style = Style.find(params[:id])
      @station.styles.destroy(@style)
      # @station.reindex
      redirect_to station_admin_station_station_styles_path(@station)
    end
  end
end

app/controllers/station_admin/style_synonyms_controller.rb
# frozen_string_literal: true

module StationAdmin
  class StyleSynonymsController < BaseController
    def index
      if current_user.operator?
        in_my_country = params.delete(:in_my_country)

        session[:in_my_country] = in_my_country

        respond_to do |format|
          format.html
          format.json do
            render json: StyleSynonymDatatable.new(params,
                                                   view_context: view_context,
                                                   in_my_country: in_my_country,
                                                   current_user: current_user)
          end
        end
      else
        redirect_to station_admin_root_url
      end
    end

    def edit
      @active_tab = 'styles'
      @style_synonym = StyleSynonym.find(params[:id])
      @styles = Style.includes(:translations) - @style_synonym.styles.includes(:translations)
    end

    def update
      @style_synonym = StyleSynonym.find(params[:id])

      @style_synonym.update!(resource_params)

      redirect_to edit_station_admin_style_synonym_path(@style_synonym)
    end

    private

    def resource_params
      params.require(:style_synonym).permit(:name).tap do |hash|
        hash[:translatable_columns_values] = params[:style_synonym][:translatable_columns_values].permit!
      end
    end
  end
end

app/controllers/station_admin/styles_controller.rb
# frozen_string_literal: true

module StationAdmin
  class StylesController < BaseController
    def index
      if current_user.operator?
        @active_tab = 'styles'

        in_my_country = params.delete(:in_my_country)

        session[:in_my_country] = in_my_country

        respond_to do |format|
          format.html
          format.json do
            render json: StyleDatatable.new(params,
                                            view_context: view_context,
                                            in_my_country: in_my_country,
                                            current_user: current_user)
          end
        end
      else
        redirect_to station_admin_root_url
      end
    end

    def edit
      @active_tab = 'styles'
      @style = Style.find(params[:id])
      @style_synonyms = StyleSynonym.includes(:translations) - @style.style_synonyms.includes(:translations)
    end

    def update
      @style = Style.find(params[:id])

      @style.update!(resource_params)

      update_permitted_countries

      redirect_to edit_station_admin_style_path(@style)
    end

    def destroy
      @style = Style.find(params[:id])

      @style.remove_country(current_user.country_code)

      redirect_to station_admin_styles_path(anchor: 'styles', in_my_country: session[:in_my_country])
    end

    private

    def resource_params
      params.require(:style).permit(:name, :slug, :tooltip, :description).tap do |hash|
        hash[:translatable_columns_values] = params[:style][:translatable_columns_values].permit!
      end
    end

    def update_permitted_countries
      if params[:in_my_country]
        @style.add_country(current_user.country_code)
      else
        @style.remove_country(current_user.country_code)
      end
    end
  end
end

app/views/station_admin/styles/edit.html.erb
<div class="page-heading">
  <h1><i class="fa fa-edit"></i> <%= t('.style_edit', scope: :hallway_styles) %></h1>
</div>

<div class="row">
  <div class="col-sm-12 ui-sortable">
    <div class="widget">
      <%= form_for [:station_admin, @style], html: { class: 'form-horizontal', role: 'form' } do |f| %>
        <div class="widget-content padding">

          <%= f.fields_for :translatable_columns_values do |tr| %>
            <% ['en', current_user.country_setting.locale].each do |locale| %>
              <div class="form-group">
                <%= tr.fields_for locale do |translation| %>
                  <%= translation.hidden_field :locale, value: locale %>
                  <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">
                      <%= "#{ I18n.with_locale(locale) { t('.name', scope: :hallway_styles) } }: #{ locale.capitalize }" %>
                    </label>
                    <div class="col-sm-10">
                      <%= translation.text_field :name,
                                                 value: I18n.with_locale(locale) { @style.name },
                                                 placeholder: t('.name', scope: :hallway_styles),
                                                 class: 'form-control',
                                                 required: 'required' %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>

          <div class="form-group">
            <label for="in_my_country" class="col-sm-2 control-label">
              <%= t('.in_my_country', scope: :hallway_styles) %>
            </label>
            <div class="col-lg-7 col-xs-10">
              <%= check_box_tag :in_my_country,
                                true,
                                @style.permitted_countries.include?(current_user.country_code),
                                { class: 'form-control selectpicker' } %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-lg-9 col-xs-12">
              <div class="text-right">
                <%= f.submit t('.save', scope: :hallway_styles), class: 'btn btn-default' %>
              </div>
            </div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 ui-sortable">
    <%= form_tag station_admin_style_manage_style_synonyms_path(@style) do %>
      <%= select_tag :id,
                     options_from_collection_for_select(@style_synonyms, 'id', 'name'),
                     class: 'selectpicker',
                     'data-live-search' => 'true' %>
      <button type="submit" class="btn btn-success">
        <%= t('.add', scope: :hallway_styles) %>
      </button>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 ui-sortable">
    <div class="widget">
      <div class="widget-content padding">
        <br>
        <form class="form-horizontal" role="form">
          <table class="datatables table table-striped" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>ID</th>
                <th><%= t('.name', scope: :hallway_styles) %></th>
                <th><%= t('.synonym_edit', scope: :hallway_styles) %></th>
                <th><%= t('.unbind', scope: :hallway_styles) %></th>
              </tr>
            </thead>
            <tbody>
              <% @style.style_synonyms.each do |synonym| %>
                <tr>
                  <td><%= synonym.id %></td>
                  <td><%= synonym.name %></td>
                  <td><%= link_to t('.synonym_edit', scope: :hallway_styles),
                                  edit_station_admin_style_synonym_path(synonym) %></td>
                  <td>
                    <%= link_to t('.unbind', scope: :hallway_styles),
                                station_admin_style_manage_style_synonym_path(@style, synonym),
                                method: :delete,
                                data: { confirm: t('.unbind', scope: :hallway_styles) } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/station_admin/styles/index.html.erb
<div class="btn-group btn-group-country" role="tablist">
  <%= link_to t('.all', scope: :hallway_styles),
              station_admin_styles_path,
              class: "btn btn-default btn-categories-country #{ 'active' unless session[:in_my_country] }" %>
  <%= link_to t('.in_my_country', scope: :hallway_styles),
              station_admin_styles_path(in_my_country: true),
              class: "btn btn-default btn-categories-country #{ 'active' if session[:in_my_country] }" %>
</div>

<br>

<div class="btn-group nav-services" role="tablist">
  <a href="#styles" aria-controls="styles" role="tab" data-toggle="tab" class="btn btn-primary btn-categories-services"><%= t('.styles', scope: :hallway_styles) %></a>
  <a href="#style_synonyms" aria-controls="style_synonyms" role="tab" data-toggle="tab" class="btn btn-primary btn-categories-services"><%= t('.style_synonyms', scope: :hallway_styles) %></a>
</div>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="styles">
    <div class="row">
      <div class="col-sm-12 ui-sortable">
        <div class="widget">
          <div class="widget-content padding">
            <form class="form-horizontal" role="form">
              <table class="table table-striped" cellspacing="0" width="100%" id="styles-datatable"
                     data-source="<%= station_admin_styles_path(format: :json, in_my_country: session[:in_my_country]) %>">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th><%= t('.style_name', scope: :hallway_styles) %></th>
                    <th><%= t('.in_my_country', scope: :hallway_styles) %></th>
                    <th><%= t('.edit', scope: :hallway_styles) %></th>
                    <th><%= t('.delete', scope: :hallway_styles) %></th>
                  </tr>
                </thead>
                <tbody></tbody>
              </table>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="style_synonyms">
    <div class="row">
      <div class="col-sm-12 ui-sortable">
        <div class="widget">
          <div class="widget-content padding">
            <form class="form-horizontal" role="form">
              <table class="table table-striped" id="style-synonyms-datatable" cellspacing="0" width="100%"
                     data-source="<%= station_admin_style_synonyms_path(format: :json, in_my_country: session[:in_my_country]) %>">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th><%= t('.text', scope: :hallway_styles) %></th>
                    <th><%= t('.in_my_country', scope: :hallway_styles) %></th>
                    <th><%= t('.edit', scope: :hallway_styles) %></th>
                  </tr>
                </thead>
                <tbody></tbody>
              </table>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>