config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, format: :json do
    resources :stations, only: [] do
      resources :styles, only: :index, controller: :station_styles
    end
  end

  namespace :station_admin do
    resources :stations, only: [] do
      resources :station_styles, only: [:index, :create, :destroy]
    end

    resources :styles, only: [:index, :edit, :update, :destroy] do
      resources :manage_style_synonyms, only: [:create, :destroy]
    end

    resources :style_synonyms, only: [:index, :edit, :update] do
      resources :manage_styles, only: [:create, :destroy]
    end
  end
end

app/models/style_synonym.rb
# frozen_string_literal: true

require 'globalize'

class StyleSynonym < ApplicationRecord
  include TranslationsConcern

  has_many :style_style_synonyms, dependent: :destroy

  has_many :styles, through: :style_style_synonyms

  translates :name

  scope :with_country, ->(code) { where('? = ANY(permitted_countries)', code) }
end

app/controllers/station_admin/base_controller.rb
# frozen_string_literal: true

if !Object.const_defined?('StationAdmin::BaseController')
  module StationAdmin
    class BaseController < ActionController::Base
      layout 'application'
    end
  end
end

app/controllers/station_admin/manage_style_synonyms_controller.rb
# frozen_string_literal: true

module StationAdmin
  class ManageStyleSynonymsController < BaseController
    def create
      @style = Style.find(params[:style_id])
      @style_synonym = StyleSynonym.find(params[:id])
      @style.style_synonyms << @style_synonym
      # @style.reindex
      redirect_to edit_station_admin_style_path(@style)
    end

    def destroy
      @style = Style.find(params[:style_id])
      @style_synonym = StyleSynonym.find(params[:id])
      @style.style_synonyms.destroy(@style_synonym)
      # @style.reindex
      redirect_to edit_station_admin_style_path(@style)
    end
  end
end

app/controllers/station_admin/manage_styles_controller.rb
# frozen_string_literal: true

module StationAdmin
  class ManageStylesController < BaseController
    def create
      @style_synonym = StyleSynonym.find(params[:style_synonym_id])
      @style = Style.find(params[:id])
      @style_synonym.styles << @style
      # @style_synonym.reindex
      redirect_to edit_station_admin_style_synonym_path(@style_synonym)
    end

    def destroy
      @style_synonym = StyleSynonym.find(params[:style_synonym_id])
      @style = Style.find(params[:id])
      @style_synonym.styles.destroy(@style)
      # @style_synonym.reindex
      redirect_to edit_station_admin_style_synonym_path(@style_synonym)
    end
  end
end

app/controllers/station_admin/station_styles_controller.rb
# frozen_string_literal: true

module StationAdmin
  class StationStylesController < BaseController
    def index
      @station = Station.find(params[:station_id])
      @active_tab = 'station_styles'
      params[:display_menu_for_station] = true
      @styles = Style.includes(:translations)
                     .with_country(current_user.country_code) - @station.styles.includes(:translations)

      respond_to do |format|
        format.html
        format.json do
          render json: StationStyleDatatable.new(params,
                                                 station: @station,
                                                 view_context: view_context)
        end
      end
    end

    def create
      @station = Station.find(params[:station_id])
      @style = Style.find(params[:id])
      @station.styles << @style
      # @station.reindex
      redirect_to station_admin_station_station_styles_path(@station)
    end

    def destroy
      @station = Station.find(params[:station_id])
      @style = Style.find(params[:id])
      @station.styles.destroy(@style)
      # @station.reindex
      redirect_to station_admin_station_station_styles_path(@station)
    end
  end
end

app/controllers/station_admin/style_synonyms_controller.rb
# frozen_string_literal: true

module StationAdmin
  class StyleSynonymsController < BaseController
    def index
      if current_user.operator?
        in_my_country = params.delete(:in_my_country)

        session[:in_my_country] = in_my_country

        respond_to do |format|
          format.html
          format.json do
            render json: StyleSynonymDatatable.new(params,
                                                   view_context: view_context,
                                                   in_my_country: in_my_country,
                                                   current_user: current_user)
          end
        end
      else
        redirect_to station_admin_root_url
      end
    end

    def edit
      @active_tab = 'styles'
      @style_synonym = StyleSynonym.find(params[:id])
      @styles = Style.includes(:translations) - @style_synonym.styles.includes(:translations)
    end

    def update
      @style_synonym = StyleSynonym.find(params[:id])

      @style_synonym.update!(resource_params)

      redirect_to edit_station_admin_style_synonym_path(@style_synonym)
    end

    private

    def resource_params
      params.require(:style_synonym).permit(:name).tap do |hash|
        hash[:translatable_columns_values] = params[:style_synonym][:translatable_columns_values].permit!
      end
    end
  end
end

app/controllers/station_admin/styles_controller.rb
# frozen_string_literal: true

module StationAdmin
  class StylesController < BaseController
    def index
      if current_user.operator?
        @active_tab = 'styles'

        in_my_country = params.delete(:in_my_country)

        session[:in_my_country] = in_my_country

        respond_to do |format|
          format.html
          format.json do
            render json: StyleDatatable.new(params,
                                            view_context: view_context,
                                            in_my_country: in_my_country,
                                            current_user: current_user)
          end
        end
      else
        redirect_to station_admin_root_url
      end
    end

    def edit
      @active_tab = 'styles'
      @style = Style.find(params[:id])
      @style_synonyms = StyleSynonym.includes(:translations) - @style.style_synonyms.includes(:translations)
    end

    def update
      @style = Style.find(params[:id])

      @style.update!(resource_params)

      update_permitted_countries

      redirect_to edit_station_admin_style_path(@style)
    end

    def destroy
      @style = Style.find(params[:id])

      @style.remove_country(current_user.country_code)

      redirect_to station_admin_styles_path(anchor: 'styles', in_my_country: session[:in_my_country])
    end

    private

    def resource_params
      params.require(:style).permit(:name, :slug, :tooltip, :description).tap do |hash|
        hash[:translatable_columns_values] = params[:style][:translatable_columns_values].permit!
      end
    end

    def update_permitted_countries
      if params[:in_my_country]
        @style.add_country(current_user.country_code)
      else
        @style.remove_country(current_user.country_code)
      end
    end
  end
end

app/views/station_admin/style_synonyms/edit.html.erb
<div class="page-heading">
  <h1><i class="fa fa-edit"></i> <%= t('.style_synonym_edit', scope: :hallway_styles) %></h1>
</div>

<div class="row">
  <div class="col-sm-12 ui-sortable">
    <div class="widget">
      <%= form_for [:station_admin, @style_synonym],
                   html: { class: 'form-horizontal', role: 'form' } do |f| %>
        <div class="widget-content padding">

          <%= f.fields_for :translatable_columns_values do |tr| %>
            <% ['en', current_user.country_setting.locale].each do |locale| %>
              <div class="form-group">
                <%= tr.fields_for locale do |translation| %>
                  <%= translation.hidden_field :locale, value: locale %>
                  <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">
                      <%= "#{ I18n.with_locale(locale) { t('.title', scope: :hallway_styles) } }: #{ locale.capitalize }" %>
                    </label>
                    <div class="col-sm-10">
                      <%= translation.text_field :name,
                                                 value: I18n.with_locale(locale) { @style_synonym.name },
                                                 placeholder: t('.title', scope: :hallway_styles),
                                                 class: 'form-control',
                                                 required: 'required' %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>

          <div class="form-group">
            <div class="col-lg-9 col-xs-12">
              <div class="text-right">
                <%= f.submit t('.save', scope: :hallway_styles), class: 'btn btn-default' %>
              </div>
            </div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 ui-sortable">
    <%= form_tag station_admin_style_synonym_manage_styles_path(@style_synonym) do %>
      <%= select_tag :id,
                     options_from_collection_for_select(@styles, 'id', 'name'),
                     class: 'selectpicker',
                     'data-live-search' => 'true' %>
      <button type="submit" class="btn btn-success">
        <%= t('.add', scope: :hallway_styles) %>
      </button>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 ui-sortable">
    <div class="widget">
      <div class="widget-content padding">
        <form class="form-horizontal" role="form">
          <table class="datatables table table-striped" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>ID</th>
                <th><%= t('.name', scope: :hallway_styles) %></th>
                <th><%= t('.style_edit', scope: :hallway_styles) %></th>
                <th><%= t('.unbind', scope: :hallway_styles) %></th>
              </tr>
            </thead>
            <tbody>
              <% @style_synonym.styles.each do |style| %>
                <tr>
                  <td><%= style.id %></td>
                  <td><%= style.name %></td>
                  <td><%= link_to t('.style_edit', scope: :hallway_styles),
                                  edit_station_admin_style_path(style) %></td>
                  <td>
                    <%= link_to t('.unbind', scope: :hallway_styles),
                                station_admin_style_synonym_manage_style_path(@style_synonym, style),
                                method: :delete,
                                data: { confirm: t('.unbind', scope: :hallway_styles) } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </form>
      </div>
    </div>
  </div>
</div>